hello_world_script:
  class: File
  path: scripts/helloworld.sh
duplicator_script:
  class: File
  path: path/here
make_caps_script:
  class: File
  path: path/here
names:
  - Jamie
  - Jameson
numbers:
  - 1
  - 2
  - 3
  - 4
  - 5
